### ISSUE TITLE
pre train model

### ISSUE THREAD

**Issue by Shanzaay** [JaywongWang/DenseVideoCaptioning#16]
Hi. I am kinda newbie in all this. I want to try to run the pre-train models. 
Can you guide me a bit, how can I use the pre-train models? a little guidance will do the job.

Thanks in advance

**Comment by JaywongWang** [comment]
Since the model is pre-trained on ActivityNet Captions (https://cs.stanford.edu/people/ranjaykrishna/densevid/) using the provided C3D features (I down-sampled 8 times), you may need to first extract C3D features for a new video and then perform PCA to obtain 500-d vectors (http://activity-net.org/challenges/2016/download.html#c3d). After that, run test.py to generate captions for the video.

**Comment by Shanzaay** [comment]
I only need to extract C3D features in i want to train the model on my own videos right? 
If i use the provided C3D features then i don't need to extract the C3D features?

**Comment by JaywongWang** [comment]
Yes. If you just want to caption the ActivityNet videos, no feature extraction is needed (you can directly use the provided C3D features). If you want to caption other videos, you may need to extract C3D features and do similar processing (i.e., PCA).

**Comment by Shanzaay** [comment]
Thanks a bunch.
